# Site settings
title: Can Hack
header-img: img/home-bg.jpg
email: you@canhack.it
description: "Can Hack. Hackspace en Mallorca"
baseurl: ""
url: "http://canhack.github.io"
twitter_username: youcanhackit
github_username:  CanHack
linkedin_username:  Can-Hack-8235926/about

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
